// Generated by scripts/build-brand.mts from the <LogoMark> geometry. Do not edit.
export const LOGO = {
  "canvas": "M13 3L5 3Q3 3 3 5L3 19Q3 21 5 21L19 21Q21 21 21 19L21 11",
  "trail": [
    "M7.5 16.5l2-2",
    "M11.5 12.5l2-2"
  ],
  "badge": "M18.5 2.5L19.5 2.5Q21.5 2.5 21.5 4.5L21.5 5.5Q21.5 7.5 19.5 7.5L18.5 7.5Q16.5 7.5 16.5 5.5L16.5 4.5Q16.5 2.5 18.5 2.5Z",
  "colors": {
    "accent": "#2563eb",
    "trail": "#10b981",
    "ink": "#0a0a0a",
    "paper": "#fafafa"
  }
} as const
