// Regenerates everything derived from the icon files, so adding an icon is just adding its file:
//   src/icons/index.ts  the barrel
//   registry.json       the core's file list, one shadcn registry item per icon, plus `all`
//   catalog.json        every icon's `meta`, for agents to search (skills/find-animated-icon); the site
//                       serves a copy at /icons.json
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

import { runnerImport } from "vite"

const root = fileURLToPath(new URL("..", import.meta.url))
// Registry items depend on each other by full URL, so installs work with or without the @kovenlabs
// namespace in the user's components.json. The URL has one home: the site's config.
const site = JSON.parse(readFileSync(new URL("../../../apps/web/site.config.json", import.meta.url), "utf8"))
const SITE_URL = (process.env.SITE_URL ?? site.url).replace(/\/$/, "")
const itemUrl = (name) => `${SITE_URL}/r/${name}.json`
const iconsDir = `${root}src/icons`

const icons = readdirSync(iconsDir)
  .filter((file) => file.endsWith(".tsx"))
  .sort()
  .map((file) => {
    const name = file.replace(/\.tsx$/, "")
    const source = readFileSync(`${iconsDir}/${file}`, "utf8")
    const exportName = source.match(/export const (\w+) = createAnimatedIcon/)?.[1]
    if (!exportName) throw new Error(`${file}: expected \`export const <Name> = createAnimatedIcon(...)\``)
    // the JSDoc right above the export: it may not span another comment's end, or it would swallow code
    const doc = source
      .match(/\/\*\*((?:(?!\*\/)[\s\S])*?)\*\/\s*export const/)?.[1]
      .split("/**")
      .at(-1)
      .replace(/\s*\n\s*\*?\s*/g, " ")
      .trim()
    return { name, file, exportName, doc }
  })

writeFileSync(
  `${iconsDir}/index.ts`,
  `// Generated by scripts/generate.mjs. Do not edit: add or remove icon files instead.\n// Each icon is exported by its name (Bell) and as BellIcon, for when a name collides with another\n// component in your code (shadcn/ui Calendar, next/link Link, the DOM Image).\n${icons
    .map((icon) => `export { ${icon.exportName}, ${icon.exportName} as ${icon.exportName}Icon } from "./${icon.name}"`)
    .join("\n")}\n`,
)

const registryPath = `${root}registry.json`
const registry = JSON.parse(readFileSync(registryPath, "utf8"))
registry.homepage = SITE_URL
const core = registry.items.find((item) => item.name === "animated-icons")
// the core ships every file in src/lib, plus config.ts: listed from disk, never by hand
const libFiles = readdirSync(`${root}src/lib`).filter((file) => /\.tsx?$/.test(file)).sort()
core.files = [
  ...libFiles.map((file) => ({
    path: `src/lib/${file}`,
    type: "registry:lib",
    target: `components/animated-icons/lib/${file}`,
  })),
  { path: "src/config.ts", type: "registry:file", target: "components/animated-icons/config.ts" },
]
const title = (name) => name.replace(/(^|-)(\w)/g, (_, dash, c) => (dash ? " " : "") + c.toUpperCase())

registry.items = [
  core,
  // `npx shadcn add @kovenlabs/all`: the whole set (each icon pulls in the core)
  {
    name: "all",
    type: "registry:item",
    title: "All animated icons",
    description: `Every icon in the set (${icons.length}), plus the core.`,
    registryDependencies: icons.map((icon) => itemUrl(icon.name)),
    files: [],
  },
  ...icons.map((icon) => ({
    name: icon.name,
    type: "registry:component",
    title: `${title(icon.name)} icon`,
    description: icon.doc ?? `${title(icon.name)} animated icon.`,
    registryDependencies: [itemUrl("animated-icons")],
    files: [
      {
        path: `src/icons/${icon.file}`,
        type: "registry:component",
        target: `components/animated-icons/icons/${icon.file}`,
      },
    ],
  })),
]
writeFileSync(registryPath, `${JSON.stringify(registry, null, 2)}\n`)

// The catalog is read from each icon's real `meta`, loaded through vite (the icons are TSX), never re-parsed
// from source: it can't drift from what the components report.
const { module: library } = await runnerImport(`${root}src/index.ts`, { configFile: false, logLevel: "error" })
const docs = new Map(icons.map((icon) => [icon.name, icon.doc]))
const catalog = {
  $comment: "Generated by scripts/generate.mjs from each icon's meta. Do not edit.",
  version: JSON.parse(readFileSync(`${root}package.json`, "utf8")).version,
  site: SITE_URL,
  icons: [...new Set(Object.values(library).filter((value) => typeof value === "function" && "meta" in value))]
    .sort((a, b) => a.meta.name.localeCompare(b.meta.name))
    .map((icon) => ({ ...icon.meta, component: icon.displayName, description: docs.get(icon.meta.name) })),
}
// one icon per line: a diff shows exactly which icons changed, at a third of the pretty-printed size
const { icons: entries, ...head } = catalog
const catalogJson = `${JSON.stringify(head, null, 2).slice(0, -2)},\n  "icons": [\n${entries
  .map((entry) => `    ${JSON.stringify(entry)}`)
  .join(",\n")}\n  ]\n}\n`
writeFileSync(`${root}catalog.json`, catalogJson)
const publicDir = `${root}../../apps/web/public`
mkdirSync(publicDir, { recursive: true })
writeFileSync(`${publicDir}/icons.json`, catalogJson)

console.log(`generated ${icons.length} icons: ${icons.map((icon) => icon.name).join(", ")}`)
