// Regenerates everything derived from the icon files, so adding an icon is just adding its file:
//   src/icons/index.ts  the barrel
//   registry.json       the core's file list, one shadcn registry item per icon, plus `all`
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

const root = fileURLToPath(new URL("..", import.meta.url))
// Registry items depend on each other by full URL, so installs work with or without the @kovenlabs
// namespace in the user's components.json. The URL has one home: the site's config.
const site = JSON.parse(readFileSync(new URL("../../../apps/web/site.config.json", import.meta.url), "utf8"))
const SITE_URL = (process.env.SITE_URL ?? site.url).replace(/\/$/, "")
const itemUrl = (name) => `${SITE_URL}/r/${name}.json`
const iconsDir = `${root}src/icons`

const icons = readdirSync(iconsDir)
  .filter((file) => file.endsWith(".tsx"))
  .sort()
  .map((file) => {
    const name = file.replace(/\.tsx$/, "")
    const source = readFileSync(`${iconsDir}/${file}`, "utf8")
    const exportName = source.match(/export const (\w+Icon) = createAnimatedIcon/)?.[1]
    if (!exportName) throw new Error(`${file}: expected \`export const <Name>Icon = createAnimatedIcon(...)\``)
    const doc = source.match(/\/\*\*\s*(.+?)\s*\*\/\s*export const/s)?.[1].replace(/\s*\n\s*\*?\s*/g, " ")
    return { name, file, exportName, doc }
  })

writeFileSync(
  `${iconsDir}/index.ts`,
  `// Generated by scripts/generate.mjs. Do not edit: add or remove icon files instead.\n${icons
    .map((icon) => `export { ${icon.exportName} } from "./${icon.name}"`)
    .join("\n")}\n`,
)

const registryPath = `${root}registry.json`
const registry = JSON.parse(readFileSync(registryPath, "utf8"))
registry.homepage = SITE_URL
const core = registry.items.find((item) => item.name === "animated-icons")
// the core ships every file in src/lib, plus config.ts: listed from disk, never by hand
const libFiles = readdirSync(`${root}src/lib`).filter((file) => /\.tsx?$/.test(file)).sort()
core.files = [
  ...libFiles.map((file) => ({
    path: `src/lib/${file}`,
    type: "registry:lib",
    target: `components/animated-icons/lib/${file}`,
  })),
  { path: "src/config.ts", type: "registry:file", target: "components/animated-icons/config.ts" },
]
const title = (name) => name.replace(/(^|-)(\w)/g, (_, dash, c) => (dash ? " " : "") + c.toUpperCase())

registry.items = [
  core,
  // `npx shadcn add @kovenlabs/all`: the whole set (each icon pulls in the core)
  {
    name: "all",
    type: "registry:item",
    title: "All animated icons",
    description: `Every icon in the set (${icons.length}), plus the core.`,
    registryDependencies: icons.map((icon) => itemUrl(icon.name)),
    files: [],
  },
  ...icons.map((icon) => ({
    name: icon.name,
    type: "registry:component",
    title: `${title(icon.name)} icon`,
    description: icon.doc ?? `${title(icon.name)} animated icon.`,
    registryDependencies: [itemUrl("animated-icons")],
    files: [
      {
        path: `src/icons/${icon.file}`,
        type: "registry:component",
        target: `components/animated-icons/icons/${icon.file}`,
      },
    ],
  })),
]
writeFileSync(registryPath, `${JSON.stringify(registry, null, 2)}\n`)

console.log(`generated ${icons.length} icons: ${icons.map((icon) => icon.name).join(", ")}`)
